// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv5kwx1dJ2PLcsV3ONs5a29c5Y2OFxMWo',
    appId: '1:627243814142:web:30567666ebcfe1fc4d69af',
    messagingSenderId: '627243814142',
    projectId: 'osh-mobile-2c3c6',
    authDomain: 'osh-mobile-2c3c6.firebaseapp.com',
    storageBucket: 'osh-mobile-2c3c6.firebasestorage.app',
    measurementId: 'G-GHHVYRMJPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF50RsjamDNgFR3oSqXcPx0x_237voWDA',
    appId: '1:627243814142:android:88de377118f34d3c4d69af',
    messagingSenderId: '627243814142',
    projectId: 'osh-mobile-2c3c6',
    storageBucket: 'osh-mobile-2c3c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80fu7Bg--HCu8wiLbtlMS-euiIda6ZqM',
    appId: '1:627243814142:ios:b5a92f44dcdf1ed74d69af',
    messagingSenderId: '627243814142',
    projectId: 'osh-mobile-2c3c6',
    storageBucket: 'osh-mobile-2c3c6.firebasestorage.app',
    iosBundleId: 'com.oshmobile.oshmobile',
  );
}
